name: Package and Release

on:
  push:
    tags:
      - '*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GH_ACTIONS_RELEASE_TOKEN }}
          tag: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          body: Initial release creation
          draft: false
          prerelease: false
          allowUpdates: true

  build:
    runs-on: ${{ matrix.os }}
    needs: create_release
    strategy:
      matrix:
        include:
          # MacOS
          - os: macos-latest
            arch: x86_64
            node: 18
          - os: macos-latest
            arch: arm64
            node: 18
          - os: macos-latest
            arch: x86_64
            node: 20
          - os: macos-latest
            arch: arm64
            node: 20
          # Ubuntu
          - os: ubuntu-latest
            arch: x86_64
            node: 18
          - os: ubuntu-latest
            arch: arm64
            node: 18
          - os: ubuntu-latest
            arch: x86_64
            node: 20
          - os: ubuntu-latest
            arch: arm64
            node: 20
          # Windows
          - os: windows-latest
            arch: x86_64
            node: 18
          - os: windows-latest
            arch: x86_64
            node: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Zip files (Windows)
        if: runner.os == 'Windows'
        run: powershell.exe -Command "Compress-Archive -Path . -DestinationPath evidence-${{ matrix.os }}-${{ matrix.arch }}-node${{ matrix.node }}.zip -Force"

      - name: Zip files (Unix)
        if: runner.os != 'Windows'
        run: zip -r evidence-${{ matrix.os }}-${{ matrix.arch }}-node${{ matrix.node }}.zip . -x "*.git*"

      - name: Upload to GH release
        uses: ncipollo/release-action@v1
        with:
          artifacts: evidence-${{ matrix.os }}-${{ matrix.arch }}-node${{ matrix.node }}.zip
          token: ${{ secrets.GH_ACTIONS_RELEASE_TOKEN }}
          tag: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          body: Release for ${{ github.ref_name }}
          draft: false
          prerelease: false
          allowUpdates: true
